package pojo;
// Generated Dec 22, 2016 2:09:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Class generated by hbm2java
 */
public class Class  implements java.io.Serializable {


     private String classname;
     private Integer classgrade;
     private Date classdate;
     private String department;
     private String major;

    public Class() {
    }

	
    public Class(String classname) {
        this.classname = classname;
    }
    public Class(String classname, Integer classgrade, Date classdate, String department, String major) {
       this.classname = classname;
       this.classgrade = classgrade;
       this.classdate = classdate;
       this.department = department;
       this.major = major;
    }
   
    public String getClassname() {
        return this.classname;
    }
    
    public void setClassname(String classname) {
        this.classname = classname;
    }
    public Integer getClassgrade() {
        return this.classgrade;
    }
    
    public void setClassgrade(Integer classgrade) {
        this.classgrade = classgrade;
    }
    public Date getClassdate() {
        return this.classdate;
    }
    
    public void setClassdate(Date classdate) {
        this.classdate = classdate;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }




}


