package pojo;
// Generated Dec 22, 2016 2:09:21 PM by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String coursename;
     private String courseid;
     private String coursetype;

    public Course() {
    }

	
    public Course(String coursename) {
        this.coursename = coursename;
    }
    public Course(String coursename, String courseid, String coursetype) {
       this.coursename = coursename;
       this.courseid = courseid;
       this.coursetype = coursetype;
    }
   
    public String getCoursename() {
        return this.coursename;
    }
    
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }
    public String getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }
    public String getCoursetype() {
        return this.coursetype;
    }
    
    public void setCoursetype(String coursetype) {
        this.coursetype = coursetype;
    }




}


